export enum VerificationStatus {
  NOT_STARTED = 'NOT_STARTED',
  INITIATED = 'INITIATED',
  DOCUMENTS_PENDING = 'DOCUMENTS_PENDING',
  DOCUMENTS_RECEIVED = 'DOCUMENTS_RECEIVED',
  VERIFICATION_IN_PROGRESS = 'VERIFICATION_IN_PROGRESS',
  VENDOR_CALLBACK_AWAITED = 'VENDOR_CALLBACK_AWAITED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  ESCALATED_TO_MANUAL = 'ESCALATED_TO_MANUAL',
  EXPIRED = 'EXPIRED',
  RE_VERIFICATION_REQUIRED = 'RE_VERIFICATION_REQUIRED',
  SUSPENDED = 'SUSPENDED',
}
